const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let data={}, catalog={}, integrations={}, view='resumen', chatMessages=[], chats=[], activeChatId=null;
const titles={resumen:['Resumen ejecutivo','Datos reales de PostgreSQL · RopaV'],tendencia:['Evolución de ventas','Comportamiento mensual de ingresos y utilidad'],producto:['Rendimiento por producto','Productos que impulsan el crecimiento'],categoria:['Mezcla de categorías','Participación y rentabilidad del portafolio'],cliente:['Clientes y segmentos','Comportamiento de los segmentos de clientes'],canal:['Canales de venta','Aporte de cada canal comercial'],region:['Ventas por región','Costa, Sierra, Amazonía e Insular'],provincia:['Ventas por provincia','Distribución territorial por provincia'],inventario:['Inventario y stock','Disponibilidad y niveles mínimos por SKU'],entrega:['Estado de entregas','Seguimiento del cumplimiento logístico'],datos:['Catálogo de datos','Fuentes y métricas disponibles'],powerbi:['Power BI','Reporte conectado al Data Warehouse de RopaV'],tableau:['Tableau','Conexión en vivo al esquema public de PostgreSQL'],adaptable:['Análisis adaptable MCP','Consultas dinámicas sobre los datos del negocio']};
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n||0);
const num=n=>new Intl.NumberFormat('es-CO').format(n||0);
async function load(){let q=new URLSearchParams();[['desde','#desde'],['hasta','#hasta'],['region','#filterRegion'],['provincia','#filterProvince'],['canal','#filterChannel']].forEach(([k,s])=>{if($(s).value&&$(s).value!=='Todos')q.set(k,$(s).value)});data=await fetch('/api/dashboard?'+q).then(r=>r.json());render()}
function render(){let k=data.kpi;$('#kpis').innerHTML=[['INGRESOS TOTALES',money(k.ingresos),'Facturación acumulada','#11a99a'],['UTILIDAD ESTIMADA',money(k.utilidad),`${k.margen}% de margen`,'#ff9f68'],['TRANSACCIONES',num(k.transacciones),'Ventas no canceladas','#56c5d0'],['UNIDADES VENDIDAS',num(k.unidades),'Volumen comercial','#8576d4'],['CLIENTES ÚNICOS',num(k.clientes),'Base activa','#e57b9b']].map(x=>`<article class="kpi" style="--accent:${x[3]}"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></article>`).join('');let dim=view==='resumen'?'tendencia':view;let rows=data[dim]||data.tendencia;$('#chartTitle').textContent=view==='resumen'?'Ingresos y utilidad por mes':titles[view][0];drawChart(rows);renderRanking(data[view==='resumen'?'canal':view]||data.canal);$('#sideTitle').textContent=view==='inventario'?'Stock disponible / mínimo':`Distribución por ${view==='resumen'?'canal':view}`;$('#salesBody').innerHTML=data.recientes.map(r=>`<tr><td>${r.fecha}</td><td><b>${r.producto}</b></td><td>${r.region}</td><td>${r.provincia}</td><td>${r.canal}</td><td>${r.vendedor}</td><td>${r.cantidad}</td><td><b>${money(r.total)}</b></td><td><button title="Cancelar venta" onclick="removeSale(${r.id})">×</button></td></tr>`).join('');$('#rowCount').textContent=`${data.recientes.length} registros`}
function drawChart(rows){let c=$('#mainChart'),dpr=devicePixelRatio||1,w=c.clientWidth,h=260;c.width=w*dpr;c.height=h*dpr;let x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);if(!rows.length)return;let pad={l:15,r:15,t:20,b:45},max=Math.max(...rows.map(r=>r.ingresos),1),step=(w-pad.l-pad.r)/rows.length;x.strokeStyle='#e8edf1';x.lineWidth=1;for(let i=0;i<5;i++){let y=pad.t+i*(h-pad.t-pad.b)/4;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke()}rows.forEach((r,i)=>{let bw=Math.min(38,step*.48),bh=(r.ingresos/max)*(h-pad.t-pad.b),xx=pad.l+i*step+(step-bw)/2,yy=h-pad.b-bh;x.fillStyle='#17a99a';x.beginPath();x.roundRect(xx,yy,bw,bh,4);x.fill();if(r.utilidad!=null){let uh=(r.utilidad/max)*(h-pad.t-pad.b);x.fillStyle='#ff9f68';x.fillRect(xx+bw*.62,h-pad.b-uh,bw*.38,uh)}x.fillStyle='#728096';x.font='10px Segoe UI';x.textAlign='center';let label=(r.etiqueta||'').length>12?(r.etiqueta||'').slice(0,10)+'…':r.etiqueta;x.fillText(label,xx+bw/2,h-19)})}
function renderRanking(rows){let max=Math.max(...rows.map(r=>r.ingresos),1),total=rows.reduce((a,r)=>a+r.ingresos,0),plain=['inventario','entrega'].includes(view);$('#ranking').innerHTML=rows.slice(0,8).map(r=>`<div class="rank-row"><div class="rank-top"><b>${r.etiqueta}</b><small>${plain?num(r.ingresos)+' unidades':money(r.ingresos)} · ${total?Math.round(r.ingresos/total*100):0}%</small></div><div class="bar"><span style="width:${r.ingresos/max*100}%;background:${r.alerta?'#e66d6d':''}"></span></div></div>`).join('')}
async function removeSale(id){if(!confirm('¿Eliminar esta venta?'))return;await fetch('/api/ventas/'+id,{method:'DELETE'});toast('Venta eliminada');load()}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
async function init(){catalog=await fetch('/api/catalogo').then(r=>r.json());let fill=(s,a,label=x=>x,value=x=>x)=>$(s).insertAdjacentHTML('beforeend',a.map(x=>`<option value="${value(x)}">${label(x)}</option>`).join(''));fill('#filterRegion',catalog.regiones);fill('#filterProvince',catalog.provincias);fill('#filterChannel',catalog.canales,x=>x.nombre,x=>x.nombre);fill('[name=id_canal]',catalog.canales,x=>x.nombre,x=>x.id);fill('[name=id_cliente]',catalog.clientes,x=>x.nombre,x=>x.id);fill('[name=id_admin]',catalog.administradores,x=>x.nombre,x=>x.id);fill('[name=id_metodo_pago]',catalog.metodos,x=>x.nombre,x=>x.id);fill('[name=id_variante]',catalog.productos,x=>`${x.nombre} · stock ${x.stock}`,x=>x.id);$('[name=fecha]').value=new Date().toISOString().slice(0,10);$('[name=id_variante]').onchange=setPrice;setPrice();let status=await fetch('/api/chat/status').then(r=>r.json());$('#aiNavStatus').textContent=status.ia_configurada?status.modelo:'Sin API key';$('#aiNavStatus').className=status.ia_configurada?'ready':'off';await load()}
function setPrice(){let p=catalog.productos.find(x=>String(x.id)===$('[name=id_variante]').value);if(p)$('[name=precio]').value=p.precio}
$$('#nav button').forEach(b=>b.onclick=()=>{$$('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;$('#viewTitle').textContent=titles[view][0];$('#viewSubtitle').textContent=titles[view][1];let special=['adaptable','powerbi','tableau','datos'].includes(view);$('#standardView').classList.toggle('hidden',special);$('#kpis').classList.toggle('hidden',special);$('.filters').classList.toggle('hidden',special);$('#adaptiveView').classList.toggle('hidden',view!=='adaptable');$('#dataContextView').classList.toggle('hidden',view!=='datos');$('#powerbiView').classList.toggle('hidden',view!=='powerbi');$('#tableauView').classList.toggle('hidden',view!=='tableau');if(!special)render();if(view==='powerbi')loadIntegrations();if(view==='tableau')loadTableauIntegration()});
['#desde','#hasta','#filterRegion','#filterProvince','#filterChannel'].forEach(s=>$(s).onchange=load);$('#clearFilters').onclick=()=>{$$('#desde,#hasta').forEach(x=>x.value='');$('#filterRegion').value=$('#filterChannel').value='Todos';load()};
$('#newSale').onclick=()=>$('#saleDialog').showModal();$('#closeDialog').onclick=$('#cancelDialog').onclick=()=>$('#saleDialog').close();$('#saleForm').onsubmit=async e=>{e.preventDefault();let body=Object.fromEntries(new FormData(e.target));let r=await fetch('/api/ventas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)return toast(j.error);$('#saleDialog').close();toast('Venta registrada · panel actualizado');e.target.reset();$('[name=fecha]').value=new Date().toISOString().slice(0,10);setPrice();load()};
function addChat(role,text,meta='',chart=null,dashboard=null){let empty=$('.chat-empty');if(empty)empty.remove();let row=document.createElement('div'),bubble=document.createElement('div');row.className='chat-message '+role;bubble.className='chat-bubble';if(role==='assistant'&&window.ChatTables){try{ChatTables.render(bubble,text)}catch(error){console.warn('No se pudo presentar la tabla',error);bubble.textContent=text}}else bubble.textContent=text;if(meta){let small=document.createElement('small');small.className='chat-meta';small.textContent=meta;bubble.appendChild(small)}row.appendChild(bubble);$('#answer').appendChild(row);if(chart){try{attachChart(bubble,chart)}catch(error){console.error('No se pudo restaurar el gráfico',error);let note=document.createElement('small');note.className='chat-meta chart-error';note.textContent='No se pudo mostrar el gráfico solicitado.';bubble.appendChild(note)}}if(dashboard){try{bubble.classList.add('has-dashboard');attachDashboard(bubble,dashboard)}catch(error){bubble.classList.remove('has-dashboard');console.error('No se pudo restaurar el dashboard',error);let note=document.createElement('small');note.className='chat-meta chart-error';note.textContent='No se pudo mostrar esta visualización guardada.';bubble.appendChild(note)}};$('#answer').scrollTop=$('#answer').scrollHeight;return row}
async function adaptive(){
 const q=$('#question').value.trim();if(!q||$('#ask').disabled)return;
 const origin=chats.find(c=>c.id===activeChatId);if(!origin)return;
 const messages=chatMessages;origin.messages=messages;
 $('#question').value='';$('#question').style.height='auto';messages.push({role:'user',content:q});saveChat();addChat('user',q);$('#ask').disabled=true;
 const loading=document.createElement('div');loading.className='chat-message assistant';loading.innerHTML='<div class="chat-bubble chat-loading"><i></i><i></i><i></i></div>';$('#answer').appendChild(loading);
 try{
  const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:messages.filter(m=>!m.error)})});
  let j;try{j=await r.json()}catch{throw new Error('El servidor devolvió una respuesta no válida. Comprueba que la aplicación esté disponible.')}
  if(!r.ok||j.ok===false)throw new Error((j.error||'No se pudo consultar la IA')+(j.reference?' Referencia: '+j.reference:''));
  if(typeof j.text!=='string'||!j.text.trim())throw new Error('La consulta terminó sin una respuesta utilizable.');
  if(chats.includes(origin)){
   messages.push({role:'assistant',content:j.text,chart:j.chart||null,dashboard:j.dashboard||null});origin.updated=Date.now();persistChats();renderChatList();
   if(activeChatId===origin.id){const tools=(j.tools||[]).map(t=>t.name).join(', ');addChat('assistant',j.text,j.model+(tools?' · MCP: '+tools:''),j.chart,j.dashboard)}
   else toast('Respuesta guardada en '+origin.title);
  }
  if((j.tools||[]).some(t=>t.name==='registrar_venta'))load();
 }catch(e){
  const text='No pude completar la consulta: '+(e instanceof TypeError?'No se pudo contactar con el servidor.':e.message);
  if(chats.includes(origin)){messages.push({role:'assistant',content:text,error:true});origin.updated=Date.now();persistChats();if(activeChatId===origin.id)addChat('assistant',text,'El mensaje original sigue guardado. Si solicitaste registrar una venta, comprueba su estado antes de repetirla.')}
 }finally{loading.remove();$('#ask').disabled=false;$('#question').focus()}
}
async function loadIntegrations(){integrations=await fetch('/api/integraciones').then(r=>r.json());let p=integrations.powerbi,d=p.dw,url=p.embed_url;$('#dwFacts').textContent=num(d.hechos);$('#dwSales').textContent=num(d.ventas);$('#dwDate').textContent='Última fecha: '+d.ultima_fecha;$('#powerBIFrame').classList.toggle('hidden',!url);$('#powerBIEmpty').classList.toggle('hidden',!!url);if(url){$('#powerBIFrame').src=url;$('#openPowerBI').href=url}}
$('#syncPowerBI').onclick=async()=>{let r=await fetch('/api/powerbi/sincronizar',{method:'POST'}),j=await r.json();if(!r.ok)return toast(j.error);toast(`Power BI listo · ${j.nuevos_hechos} registros nuevos`);loadIntegrations()};
async function loadTableauIntegration(){integrations=await fetch('/api/integraciones').then(r=>r.json());let t=integrations.tableau||{},url=t.embed_url;$('#tableauFrame').classList.toggle('hidden',!url);$('#tableauEmpty').classList.toggle('hidden',!!url);if(url){$('#tableauFrame').src=url;$('#openTableau').href=url}}

const CHAT_KEY='nexo-bi-chat-history-v1';
let storageWarningShown=false;
function persistChats(){try{localStorage.setItem(CHAT_KEY,JSON.stringify(chats));storageWarningShown=false;return true}catch(error){console.warn('No se pudo guardar el historial',error);if(!storageWarningShown){toast('No se pudo guardar el historial. Se conserva en esta pestaña; no la cierres.');storageWarningShown=true}return false}}
function renderChatList(){const box=$('#chatList');box.replaceChildren();for(const c of chats){const row=document.createElement('div');row.className='history-item '+(c.id===activeChatId?'active':'');row.dataset.id=c.id;const title=document.createElement('span');title.textContent=c.title;const button=document.createElement('button');button.title='Eliminar';button.textContent='×';row.append(title,button);box.append(row)}}
function renderChat(){let a=$('#answer');a.innerHTML='';if(!chatMessages.length){a.innerHTML='<div class="chat-empty"><span>✦</span><h2>Nexo BI está listo</h2><p>Pregunta sobre los datos del negocio.</p></div>';return}chatMessages.forEach(m=>addChat(m.role,m.content,'',m.chart,m.dashboard))}
function saveChat(){let c=chats.find(x=>x.id===activeChatId);if(!c)return;c.messages=chatMessages;c.updated=Date.now();if(c.title==='Nueva conversación'&&chatMessages[0])c.title=chatMessages[0].content.slice(0,38);persistChats();renderChatList()}
function newConversation(){let c={id:String(Date.now()),title:'Nueva conversación',updated:Date.now(),messages:[]};chats.unshift(c);activeChatId=c.id;chatMessages=[];persistChats();renderChat();renderChatList()}
function loadChats(){try{chats=JSON.parse(localStorage.getItem(CHAT_KEY))||[]}catch(e){chats=[]}if(!chats.length)newConversation();else{activeChatId=chats[0].id;chatMessages=chats[0].messages||[];renderChat();renderChatList()}}
// A resize can arrive while the initial dashboard request is still pending.
const renderLoadedDashboard=render;
render=function(){if(data&&data.kpi)return renderLoadedDashboard()};
function chartLegend(ch){
 if(['pie','doughnut'].includes(ch.type))return ch.labels.map((l,i)=>'<span><i style="background:'+ch.colors[i]+'"></i>'+escapeHtml(l)+'</span>').join('');
 if(ch.type==='boxplot')return '<span><i style="background:#11a99a"></i>Caja (IQR)</span><span><i style="background:#ff9f68"></i>Mediana</span><span><i style="background:#526177"></i>Atípicos</span>';
 if(ch.type==='stacked_bar')return ((ch.stacks&&ch.stacks[0]&&ch.stacks[0].datasets)||[]).map(d=>'<span><i style="background:'+d.color+'"></i>'+escapeHtml(d.label)+'</span>').join('');
 if(ch.type==='heatmap')return '<span><i style="background:#e8f7f5"></i>Menor intensidad</span><span><i style="background:#11a99a"></i>Mayor intensidad</span>'; if(ch.type==='scatter')return '<span><i style="background:#11a99a"></i>Cada punto representa un producto</span>';
 return (ch.datasets||[]).map(d=>'<span><i style="background:'+d.color+'"></i>'+escapeHtml(d.label)+'</span>').join('');
}
function attachChart(bubble,ch){let box=document.createElement('div');box.className='chat-chart';box.innerHTML='<h3>'+escapeHtml(ch.title)+'</h3>'+(ch.description?'<p class="chart-description">'+escapeHtml(ch.description)+'</p>':'')+'<canvas></canvas><div class="chart-legend">'+chartLegend(ch)+'</div><small>Fuente: '+escapeHtml(ch.source)+'</small>';bubble.appendChild(box);let canvas=box.querySelector('canvas'),lastWidth=0,lastDpr=0,pending=0,redraw=()=>{let width=Math.round(canvas.getBoundingClientRect().width),dpr=devicePixelRatio||1;if(!width||(width===lastWidth&&dpr===lastDpr))return;lastWidth=width;lastDpr=dpr;cancelAnimationFrame(pending);pending=requestAnimationFrame(()=>drawChatChart(canvas,ch))};requestAnimationFrame(redraw);if(window.ResizeObserver){let observer=new ResizeObserver(redraw);observer.observe(box);box._chartObserver=observer}}function drawChatChart(c,ch){let dpr=devicePixelRatio||1,horizontal=ch.orientation==='horizontal',circular=['pie','doughnut'].includes(ch.type),w=Number(c.dataset.renderWidth)||c.clientWidth||c.width||600,h=ch.type==='heatmap'?Math.max(330,(ch.y_labels||[]).length*28+85):ch.type==='stacked_bar'?380:ch.type==='boxplot'||ch.type==='pareto'||ch.secondary_axis?340:horizontal?Math.max(280,ch.labels.length*32+35):circular?340:250;c.style.height=h+'px';c.width=w*dpr;c.height=h*dpr;let x=c.getContext('2d');x.scale(dpr,dpr);if(ch.type==='boxplot')return drawBoxplotChart(x,ch,w,h);if(ch.type==='stacked_bar')return drawStackedChart(x,ch,w,h);if(ch.type==='heatmap')return drawHeatmapChart(x,ch,w,h);if(ch.type==='scatter')return drawScatterChart(x,ch,w,h);if(ch.type==='pareto')return drawParetoChart(x,ch,w,h);if(ch.secondary_axis)return drawMultiAxisLine(x,ch,w,h);let vals=(ch.datasets||[]).flatMap(d=>(d.values||[]).map(Number)),max=Math.max(...vals,1);
if(circular){let values=ch.datasets[0].values.map(Number),total=values.reduce((a,v)=>a+v,0)||1,cx=w/2,cy=h/2,r=Math.min(w,h)*.34,start=-Math.PI/2;values.forEach((v,i)=>{let end=start+v/total*Math.PI*2;x.beginPath();x.moveTo(cx,cy);x.arc(cx,cy,r,start,end);x.closePath();x.fillStyle=ch.colors[i];x.fill();x.strokeStyle='#fff';x.lineWidth=2;x.stroke();if(v/total>.045){let mid=(start+end)/2;x.fillStyle='#fff';x.font='bold 10px Segoe UI';x.textAlign='center';x.fillText(Math.round(v/total*100)+'%',cx+Math.cos(mid)*r*.68,cy+Math.sin(mid)*r*.68)}start=end});if(ch.type==='doughnut'){x.beginPath();x.arc(cx,cy,r*.52,0,Math.PI*2);x.fillStyle='#fff';x.fill();x.fillStyle='#526177';x.font='bold 13px Segoe UI';x.textAlign='center';x.fillText(String(values.reduce((a,v)=>a+v,0)),cx,cy+4)}return}
if(horizontal){x.font='10px Segoe UI';let valueText=v=>Number(v).toLocaleString('es-EC',{minimumFractionDigits:['currency','moneda'].includes(ch.value_format)?2:0,maximumFractionDigits:2}),right=Math.max(35,...vals.map(v=>x.measureText(valueText(v)).width+12)),pad={l:Math.min(145,w*0.4),r:right,t:10,b:20},step=(h-pad.t-pad.b)/ch.labels.length,bh=Math.min(20,step/(ch.datasets.length+0.3));ch.labels.forEach((lab,i)=>{x.fillStyle='#526177';x.font='10px Segoe UI';x.textAlign='right';x.fillText(lab.length>22?lab.slice(0,20)+'…':lab,pad.l-8,pad.t+i*step+step/2+3);ch.datasets.forEach((d,j)=>{let v=Number(d.values[i]||0),yy=pad.t+i*step+(step-bh*ch.datasets.length)/2+j*bh,bw=v/max*(w-pad.l-pad.r);x.fillStyle=d.color;x.fillRect(pad.l,yy,bw,bh-3);x.fillStyle='#526177';x.textAlign='left';x.fillText(valueText(v),Math.min(pad.l+bw+5,w-x.measureText(valueText(v)).width-4),yy+bh-6)})});return}
let pad={l:30,r:10,t:12,b:58},step=(w-pad.l-pad.r)/ch.labels.length,bw=ch.type==='histogram'?step*.94:Math.min(24,step/(ch.datasets.length+1));
if(['line','area'].includes(ch.type)){ch.datasets.forEach(d=>{let pts=d.values.map((v,i)=>[pad.l+i*step+step/2,h-pad.b-Number(v)/max*(h-pad.t-pad.b)]);if(ch.type==='area'){x.beginPath();x.moveTo(pts[0][0],h-pad.b);pts.forEach(p=>x.lineTo(p[0],p[1]));x.lineTo(pts[pts.length-1][0],h-pad.b);x.closePath();x.fillStyle=d.color+'44';x.fill()}if(ch.type!=='scatter'){x.beginPath();pts.forEach((p,i)=>i?x.lineTo(p[0],p[1]):x.moveTo(p[0],p[1]));x.strokeStyle=d.color;x.lineWidth=2;x.stroke()}pts.forEach(p=>{x.beginPath();x.arc(p[0],p[1],4,0,Math.PI*2);x.fillStyle=d.color;x.fill()})});drawChartLabels(x,ch,pad,step,h);return}
ch.labels.forEach((lab,i)=>{ch.datasets.forEach((d,j)=>{let v=Number(d.values[i]||0),barh=v/max*(h-pad.t-pad.b),xx=pad.l+i*step+(step-bw*ch.datasets.length)/2+j*bw;x.fillStyle=d.color;x.fillRect(xx,h-pad.b-barh,bw-2,barh)});drawOneLabel(x,lab,pad.l+i*step+step/2,h-pad.b+9)});}
function chartGrid(x,w,h,pad){x.strokeStyle='#e8edf1';x.lineWidth=1;for(let i=0;i<5;i++){let y=pad.t+i*(h-pad.t-pad.b)/4;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke()}}
function drawBoxplotChart(x,ch,w,h){let pad={l:42,r:18,t:20,b:62},all=(ch.boxes||[]).flatMap(b=>[b.min,b.q1,b.median,b.q3,b.max,...(b.outliers||[])]).map(Number),max=Math.max(...all,1),step=(w-pad.l-pad.r)/Math.max(ch.boxes.length,1);chartGrid(x,w,h,pad);let y=v=>h-pad.b-Number(v)/max*(h-pad.t-pad.b);ch.boxes.forEach((b,i)=>{let cx=pad.l+i*step+step/2,bw=Math.min(54,step*.5);x.strokeStyle='#526177';x.lineWidth=1.5;x.beginPath();x.moveTo(cx,y(b.min));x.lineTo(cx,y(b.max));x.moveTo(cx-bw*.25,y(b.min));x.lineTo(cx+bw*.25,y(b.min));x.moveTo(cx-bw*.25,y(b.max));x.lineTo(cx+bw*.25,y(b.max));x.stroke();x.fillStyle='#11a99a88';x.strokeStyle='#11a99a';x.fillRect(cx-bw/2,y(b.q3),bw,y(b.q1)-y(b.q3));x.strokeRect(cx-bw/2,y(b.q3),bw,y(b.q1)-y(b.q3));x.strokeStyle='#ff9f68';x.lineWidth=3;x.beginPath();x.moveTo(cx-bw/2,y(b.median));x.lineTo(cx+bw/2,y(b.median));x.stroke();(b.outliers||[]).forEach(v=>{x.beginPath();x.arc(cx,y(v),3,0,Math.PI*2);x.fillStyle='#526177';x.fill()});drawOneLabel(x,b.label,cx,h-pad.b+14)});x.fillStyle='#718096';x.font='10px Segoe UI';x.textAlign='left';x.fillText('USD '+max.toFixed(0),4,pad.t+4);x.fillText('0',22,h-pad.b+3)}
function drawStackedChart(x,ch,w,h){let pad={l:35,r:12,t:20,b:65},labels=ch.labels||[],stacks=ch.stacks||[],totals=[];labels.forEach((_,i)=>stacks.forEach(s=>totals.push((s.datasets||[]).reduce((a,d)=>a+Number(d.values[i]||0),0))));let max=Math.max(...totals,1),groupW=(w-pad.l-pad.r)/Math.max(labels.length,1),gap=3,bw=Math.max(5,Math.min(22,(groupW-12)/Math.max(stacks.length,1)-gap));chartGrid(x,w,h,pad);labels.forEach((lab,i)=>{let start=pad.l+i*groupW+(groupW-(bw+gap)*stacks.length)/2;stacks.forEach((stack,j)=>{let xx=start+j*(bw+gap),bottom=h-pad.b;(stack.datasets||[]).forEach(d=>{let value=Number(d.values[i]||0),bh=value/max*(h-pad.t-pad.b);bottom-=bh;x.fillStyle=d.color;x.fillRect(xx,bottom,bw,bh)});if(i===0){x.save();x.translate(xx+bw/2,h-pad.b+42);x.rotate(-.65);x.fillStyle='#718096';x.font='8px Segoe UI';x.textAlign='right';x.fillText(stack.label.slice(0,16),0,0);x.restore()}});drawOneLabel(x,lab,pad.l+i*groupW+groupW/2,h-pad.b+10)})}
function drawHeatmapChart(x,ch,w,h){let xs=ch.x_labels||ch.labels||[],ys=ch.y_labels||[],matrix=ch.matrix||[],pad={l:95,r:12,t:12,b:48},cw=(w-pad.l-pad.r)/Math.max(xs.length,1),rh=(h-pad.t-pad.b)/Math.max(ys.length,1),max=Math.max(...matrix.flat().map(Number),1);ys.forEach((label,row)=>{x.fillStyle='#526177';x.font='9px Segoe UI';x.textAlign='right';x.fillText(label.slice(0,15),pad.l-6,pad.t+row*rh+rh*.62);xs.forEach((month,col)=>{let value=Number((matrix[row]||[])[col]||0),ratio=value/max;x.fillStyle=`rgb(${Math.round(232-(215*ratio))},${Math.round(247-(78*ratio))},${Math.round(245-(91*ratio))})`;x.fillRect(pad.l+col*cw,pad.t+row*rh,Math.max(1,cw-1),Math.max(1,rh-1));if(cw>28&&rh>18){x.fillStyle=ratio>.55?'#fff':'#274052';x.font='8px Segoe UI';x.textAlign='center';x.fillText(String(value),pad.l+col*cw+cw/2,pad.t+row*rh+rh*.62)}})});xs.forEach((label,i)=>drawOneLabel(x,label,pad.l+i*cw+cw/2,h-pad.b+10))}
function drawScatterChart(x,ch,w,h){let points=ch.points||[],pad={l:48,r:22,t:20,b:55},maxX=Math.max(...points.map(p=>Number(p.x)),1),maxY=Math.max(...points.map(p=>Number(p.y)),1);chartGrid(x,w,h,pad);points.forEach((p,i)=>{let px=pad.l+Number(p.x)/maxX*(w-pad.l-pad.r),py=h-pad.b-Number(p.y)/maxY*(h-pad.t-pad.b);x.beginPath();x.arc(px,py,5,0,Math.PI*2);x.fillStyle=(ch.colors||[])[i%Math.max((ch.colors||[]).length,1)]||'#11a99a';x.globalAlpha=.8;x.fill();x.globalAlpha=1;if(points.length<=20){x.fillStyle='#526177';x.font='8px Segoe UI';x.textAlign='left';x.fillText(String(p.label).slice(0,14),px+6,py-4)}});x.fillStyle='#718096';x.font='10px Segoe UI';x.textAlign='center';x.fillText(ch.x_label||'X',pad.l+(w-pad.l-pad.r)/2,h-8);x.save();x.translate(12,pad.t+(h-pad.t-pad.b)/2);x.rotate(-Math.PI/2);x.fillText(ch.y_label||'Y',0,0);x.restore();x.textAlign='left';x.fillText('0',pad.l-10,h-pad.b+14);x.textAlign='right';x.fillText(String(maxX),w-pad.r,h-pad.b+14);x.fillText(String(Math.round(maxY)),pad.l-5,pad.t+4)}function drawParetoChart(x,ch,w,h){let pad={l:38,r:38,t:18,b:70},bars=ch.datasets[0].values.map(Number),line=ch.datasets[1].values.map(Number),max=Math.max(...bars,1),step=(w-pad.l-pad.r)/Math.max(ch.labels.length,1),bw=Math.max(5,Math.min(24,step*.7));chartGrid(x,w,h,pad);bars.forEach((v,i)=>{let bh=v/max*(h-pad.t-pad.b),xx=pad.l+i*step+(step-bw)/2;x.fillStyle=ch.datasets[0].color;x.fillRect(xx,h-pad.b-bh,bw,bh);drawOneLabel(x,ch.labels[i],xx+bw/2,h-pad.b+12)});x.beginPath();line.forEach((v,i)=>{let px=pad.l+i*step+step/2,py=h-pad.b-v/100*(h-pad.t-pad.b);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle=ch.datasets[1].color;x.lineWidth=2;x.stroke();line.forEach((v,i)=>{let px=pad.l+i*step+step/2,py=h-pad.b-v/100*(h-pad.t-pad.b);x.beginPath();x.arc(px,py,3,0,Math.PI*2);x.fillStyle=ch.datasets[1].color;x.fill()});x.fillStyle='#718096';x.font='10px Segoe UI';x.textAlign='right';x.fillText('100%',w-2,pad.t+4);x.fillText('0%',w-2,h-pad.b+3)}
function drawMultiAxisLine(x,ch,w,h){let pad={l:35,r:38,t:18,b:58},left=(ch.datasets||[]).filter(d=>d.axis!=='right'),right=(ch.datasets||[]).filter(d=>d.axis==='right'),leftMax=Math.max(...left.flatMap(d=>d.values.map(Number)),1),rightMax=Math.max(...right.flatMap(d=>d.values.map(Number)),100),step=(w-pad.l-pad.r)/Math.max(ch.labels.length,1);chartGrid(x,w,h,pad);(ch.datasets||[]).forEach(d=>{let scale=d.axis==='right'?rightMax:leftMax,pts=d.values.map((v,i)=>[pad.l+i*step+step/2,h-pad.b-Number(v)/scale*(h-pad.t-pad.b)]);x.beginPath();pts.forEach((p,i)=>i?x.lineTo(p[0],p[1]):x.moveTo(p[0],p[1]));x.strokeStyle=d.color;x.lineWidth=2;x.stroke();pts.forEach(p=>{x.beginPath();x.arc(p[0],p[1],3,0,Math.PI*2);x.fillStyle=d.color;x.fill()})});drawChartLabels(x,ch,pad,step,h);if(right.length){x.fillStyle='#8576d4';x.font='10px Segoe UI';x.textAlign='right';x.fillText(rightMax.toFixed(0)+'%',w-2,pad.t+4);x.fillText('0%',w-2,h-pad.b+3)}}function drawOneLabel(x,lab,xx,yy){x.fillStyle='#718096';x.font='9px Segoe UI';x.textAlign='center';x.save();x.translate(xx,yy);x.rotate(-.35);x.fillText(lab.length>12?lab.slice(0,10)+'…':lab,0,0);x.restore()}
function drawChartLabels(x,ch,pad,step,h){ch.labels.forEach((lab,i)=>drawOneLabel(x,lab,pad.l+i*step+step/2,h-pad.b+9))}
$('#newChat').onclick=newConversation;$('#chatList').onclick=e=>{let i=e.target.closest('.history-item');if(!i)return;if(e.target.tagName==='BUTTON'){chats=chats.filter(c=>c.id!==i.dataset.id);if(!chats.length)return newConversation();if(activeChatId===i.dataset.id){activeChatId=chats[0].id;chatMessages=chats[0].messages||[];renderChat()}persistChats();renderChatList();return}activeChatId=i.dataset.id;chatMessages=chats.find(c=>c.id===activeChatId).messages||[];renderChat();renderChatList()};

$('#ask').onclick=adaptive;$('#question').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();adaptive()}};$('#question').oninput=e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,180)+'px'};addEventListener('resize',()=>!['adaptable','powerbi','tableau'].includes(view)&&render());loadChats();init().catch(error=>{console.error('Fallo al cargar datos',error);toast('No se pudieron cargar los datos. Comprueba el servidor y recarga la página.')});
