const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let data={}, catalog={}, integrations={}, view='resumen', chatMessages=[];
const titles={resumen:['Resumen ejecutivo','Datos reales de PostgreSQL · RopaV'],tendencia:['Evolución de ventas','Comportamiento mensual de ingresos y utilidad'],producto:['Rendimiento por producto','Productos que impulsan el crecimiento'],categoria:['Mezcla de categorías','Participación y rentabilidad del portafolio'],cliente:['Clientes y segmentos','Comportamiento de los segmentos de clientes'],canal:['Canales de venta','Aporte de cada canal comercial'],inventario:['Inventario y stock','Disponibilidad y niveles mínimos por SKU'],entrega:['Estado de entregas','Seguimiento del cumplimiento logístico'],powerbi:['Power BI','Reporte conectado al Data Warehouse de RopaV'],adaptable:['Análisis adaptable MCP','Consultas dinámicas sobre los datos del negocio']};
const TABLEAU_TITLES={ventas:'1 · Ventas',inventario:'2 · Inventario',canal:'3 · Canal',productos:'4 · Productos',region:'5 · Región'};
const TABLEAU_META={
  ventas:{metricas:['Ingresos totales','Nº de ventas','Ticket promedio','% ventas fin de semana','Canal líder'],
    graficas:['Línea: evolución mensual de ingresos','Barras: fin de semana vs. laborable por canal','Barras: ranking de canales por ingresos','Líneas por canal a través del tiempo','Tabla cruzada mes × tipo de día (ticket promedio)']},
  inventario:{metricas:['Unidades disponibles','% tallas en riesgo','Margen de stock promedio','Categoría con más riesgo','Unidades vendidas totales'],
    graficas:['Barras: margen de stock por talla (color Riesgo/OK)','Barras: stock disponible por categoría','Tabla cruzada categoría × talla con semáforo','Dispersión: unidades vendidas vs. margen de stock','Ranking: top 10 tallas con menor margen']},
  canal:{metricas:['Ingresos totales','Gasto promedio por cliente','Canal líder','Categoría más rentable por canal','Nº de ventas totales'],
    graficas:['Barras agrupadas: canal × ingresos por categoría','Mapa de calor: canal × categoría (gasto promedio)','Barras: ranking de canales por gasto promedio','Treemap: categorías dentro de cada canal','Tabla detalle canal × categoría']},
  productos:{metricas:['Ganancia estimada total','% personalizado vs. estándar','Ganancia promedio','Nº de pedidos totales','Categoría más rentable'],
    graficas:['Barras apiladas: ingresos por categoría (personalizado/estándar)','Barras: ganancia estimada por categoría','Dona: participación personalizado vs. estándar','Barras: ganancia promedio por categoría','Tabla detalle categoría × tipo de producto']},
  region:{metricas:['Ingresos totales','Ticket promedio','Nº de ventas','Región líder','Categoría líder'],
    graficas:['Mapa por provincia (ya construido)','Barras: Costa/Sierra/Oriente por ingresos','Barras apiladas: provincia × categoría','Ranking: top 10 provincias por ingresos','Treemap jerárquico región → provincia']}
};
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n||0);
const num=n=>new Intl.NumberFormat('es-CO').format(n||0);
async function load(){let q=new URLSearchParams();[['desde','#desde'],['hasta','#hasta'],['region','#filterRegion'],['canal','#filterChannel']].forEach(([k,s])=>{if($(s).value&&$(s).value!=='Todos')q.set(k,$(s).value)});data=await fetch('/api/dashboard?'+q).then(r=>r.json());render()}
function render(){let k=data.kpi;$('#kpis').innerHTML=[['INGRESOS TOTALES',money(k.ingresos),'Facturación acumulada','#11a99a'],['UTILIDAD ESTIMADA',money(k.utilidad),`${k.margen}% de margen`,'#ff9f68'],['TRANSACCIONES',num(k.transacciones),'Ventas no canceladas','#56c5d0'],['UNIDADES VENDIDAS',num(k.unidades),'Volumen comercial','#8576d4'],['CLIENTES ÚNICOS',num(k.clientes),'Base activa','#e57b9b']].map(x=>`<article class="kpi" style="--accent:${x[3]}"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></article>`).join('');let dim=view==='resumen'?'tendencia':view;let rows=data[dim]||data.tendencia;$('#chartTitle').textContent=view==='resumen'?'Ingresos y utilidad por mes':titles[view][0];drawChart(rows);renderRanking(data[view==='resumen'?'canal':view]||data.canal);$('#sideTitle').textContent=view==='inventario'?'Stock disponible / mínimo':`Distribución por ${view==='resumen'?'canal':view}`;$('#salesBody').innerHTML=data.recientes.map(r=>`<tr><td>${r.fecha}</td><td><b>${r.producto}</b></td><td>${r.region}</td><td>${r.canal}</td><td>${r.vendedor}</td><td>${r.cantidad}</td><td><b>${money(r.total)}</b></td><td><button title="Cancelar venta" onclick="removeSale(${r.id})">×</button></td></tr>`).join('');$('#rowCount').textContent=`${data.recientes.length} registros`}
function drawChart(rows){let c=$('#mainChart'),dpr=devicePixelRatio||1,w=c.clientWidth,h=260;c.width=w*dpr;c.height=h*dpr;let x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);if(!rows.length)return;let pad={l:15,r:15,t:20,b:45},max=Math.max(...rows.map(r=>r.ingresos),1),step=(w-pad.l-pad.r)/rows.length;x.strokeStyle='#e8edf1';x.lineWidth=1;for(let i=0;i<5;i++){let y=pad.t+i*(h-pad.t-pad.b)/4;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke()}rows.forEach((r,i)=>{let bw=Math.min(38,step*.48),bh=(r.ingresos/max)*(h-pad.t-pad.b),xx=pad.l+i*step+(step-bw)/2,yy=h-pad.b-bh;x.fillStyle='#17a99a';x.beginPath();x.roundRect(xx,yy,bw,bh,4);x.fill();if(r.utilidad!=null){let uh=(r.utilidad/max)*(h-pad.t-pad.b);x.fillStyle='#ff9f68';x.fillRect(xx+bw*.62,h-pad.b-uh,bw*.38,uh)}x.fillStyle='#728096';x.font='10px Segoe UI';x.textAlign='center';let label=(r.etiqueta||'').length>12?(r.etiqueta||'').slice(0,10)+'…':r.etiqueta;x.fillText(label,xx+bw/2,h-19)})}
function renderRanking(rows){let max=Math.max(...rows.map(r=>r.ingresos),1),total=rows.reduce((a,r)=>a+r.ingresos,0),plain=['inventario','entrega'].includes(view);$('#ranking').innerHTML=rows.slice(0,8).map(r=>`<div class="rank-row"><div class="rank-top"><b>${r.etiqueta}</b><small>${plain?num(r.ingresos)+' unidades':money(r.ingresos)} · ${total?Math.round(r.ingresos/total*100):0}%</small></div><div class="bar"><span style="width:${r.ingresos/max*100}%;background:${r.alerta?'#e66d6d':''}"></span></div></div>`).join('')}
async function removeSale(id){if(!confirm('¿Eliminar esta venta?'))return;await fetch('/api/ventas/'+id,{method:'DELETE'});toast('Venta eliminada');load()}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
async function init(){catalog=await fetch('/api/catalogo').then(r=>r.json());let fill=(s,a,label=x=>x,value=x=>x)=>$(s).insertAdjacentHTML('beforeend',a.map(x=>`<option value="${value(x)}">${label(x)}</option>`).join(''));fill('#filterRegion',catalog.regiones);fill('#filterChannel',catalog.canales,x=>x.nombre,x=>x.nombre);fill('[name=id_canal]',catalog.canales,x=>x.nombre,x=>x.id);fill('[name=id_cliente]',catalog.clientes,x=>x.nombre,x=>x.id);fill('[name=id_admin]',catalog.administradores,x=>x.nombre,x=>x.id);fill('[name=id_metodo_pago]',catalog.metodos,x=>x.nombre,x=>x.id);fill('[name=id_variante]',catalog.productos,x=>`${x.nombre} · stock ${x.stock}`,x=>x.id);$('[name=fecha]').value=new Date().toISOString().slice(0,10);$('[name=id_variante]').onchange=setPrice;setPrice();let status=await fetch('/api/chat/status').then(r=>r.json());$('#aiNavStatus').textContent=status.ia_configurada?status.modelo:'Sin API key';$('#aiNavStatus').className=status.ia_configurada?'ready':'off';await load()}
function setPrice(){let p=catalog.productos.find(x=>String(x.id)===$('[name=id_variante]').value);if(p)$('[name=precio]').value=p.precio}
$$('#nav button').forEach(b=>b.onclick=()=>{$$('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;let isTableau=view.startsWith('tableau-');$('#viewTitle').textContent=isTableau?TABLEAU_TITLES[view.replace('tableau-','')]:titles[view][0];$('#viewSubtitle').textContent=isTableau?'Dashboard de Tableau · conexión en vivo':titles[view][1];let special=['adaptable','powerbi'].includes(view)||isTableau;$('#standardView').classList.toggle('hidden',special);$('#kpis').classList.toggle('hidden',special);$('.filters').classList.toggle('hidden',special);$('#adaptiveView').classList.toggle('hidden',view!=='adaptable');$('#powerbiView').classList.toggle('hidden',view!=='powerbi');$('#tableauView').classList.toggle('hidden',!isTableau);if(!special)render();if(view==='powerbi')loadIntegrations();if(isTableau)loadTableauIntegration()});
['#desde','#hasta','#filterRegion','#filterChannel'].forEach(s=>$(s).onchange=load);$('#clearFilters').onclick=()=>{$$('#desde,#hasta').forEach(x=>x.value='');$('#filterRegion').value=$('#filterChannel').value='Todos';load()};
$('#newSale').onclick=()=>$('#saleDialog').showModal();$('#closeDialog').onclick=$('#cancelDialog').onclick=()=>$('#saleDialog').close();$('#saleForm').onsubmit=async e=>{e.preventDefault();let body=Object.fromEntries(new FormData(e.target));let r=await fetch('/api/ventas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)return toast(j.error);$('#saleDialog').close();toast('Venta registrada · panel actualizado');e.target.reset();$('[name=fecha]').value=new Date().toISOString().slice(0,10);setPrice();load()};
function addChat(role,text,meta=''){let empty=$('.chat-empty');if(empty)empty.remove();let row=document.createElement('div'),bubble=document.createElement('div');row.className='chat-message '+role;bubble.className='chat-bubble';bubble.textContent=text;if(meta){let small=document.createElement('small');small.className='chat-meta';small.textContent=meta;bubble.appendChild(small)}row.appendChild(bubble);$('#answer').appendChild(row);$('#answer').scrollTop=$('#answer').scrollHeight;return row}
async function adaptive(){let q=$('#question').value.trim();if(!q||$('#ask').disabled)return;$('#question').value='';chatMessages.push({role:'user',content:q});addChat('user',q);$('#ask').disabled=true;let loading=document.createElement('div');loading.className='chat-message assistant';loading.innerHTML='<div class="chat-bubble chat-loading"><i></i><i></i><i></i></div>';$('#answer').appendChild(loading);try{let r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:chatMessages})}),j=await r.json();loading.remove();if(!r.ok)throw new Error(j.error||'No se pudo consultar la IA');chatMessages.push({role:'assistant',content:j.text});let tools=(j.tools||[]).map(t=>t.name).join(', ');addChat('assistant',j.text,`${j.model}${tools?' · MCP: '+tools:''}`);if((j.tools||[]).some(t=>t.name==='registrar_venta'))load()}catch(e){loading.remove();addChat('assistant','No pude completar la consulta: '+e.message,'Revisa la configuración de OpenAI')}finally{$('#ask').disabled=false;$('#question').focus()}}
async function loadIntegrations(){integrations=await fetch('/api/integraciones').then(r=>r.json());let p=integrations.powerbi,d=p.dw,url=p.embed_url;$('#dwFacts').textContent=num(d.hechos);$('#dwSales').textContent=num(d.ventas);$('#dwDate').textContent='Última fecha: '+d.ultima_fecha;$('#powerBIFrame').classList.toggle('hidden',!url);$('#powerBIEmpty').classList.toggle('hidden',!!url);if(url){$('#powerBIFrame').src=url;$('#openPowerBI').href=url}}
$('#syncPowerBI').onclick=async()=>{let r=await fetch('/api/powerbi/sincronizar',{method:'POST'}),j=await r.json();if(!r.ok)return toast(j.error);toast(`Power BI listo · ${j.nuevos_hechos} registros nuevos`);loadIntegrations()};
async function loadTableauIntegration(){integrations=await fetch('/api/integraciones').then(r=>r.json());let objetivos=(integrations.tableau||{}).objetivos||[],id=view.replace('tableau-',''),o=objetivos.find(x=>x.id===id)||{},meta=TABLEAU_META[id]||{metricas:[],graficas:[]};$('#tableauHeroTitle').textContent=o.titulo||'Objetivo de Tableau';$('#tableauHeroPregunta').textContent=o.pregunta||'';$('#tableauCardTitle').textContent=o.titulo||'';$('#tableauFrame').classList.toggle('hidden',!o.embed_url);$('#tableauEmpty').classList.toggle('hidden',!!o.embed_url);if(o.embed_url){$('#tableauFrame').src=o.embed_url;$('#openTableau').href=o.embed_url}else{$('#openTableau').removeAttribute('href')}$('#tableauMetricas').innerHTML=meta.metricas.map(m=>`<li>${m}</li>`).join('');$('#tableauGraficas').innerHTML=meta.graficas.map(g=>`<li>${g}</li>`).join('')}
$('#ask').onclick=adaptive;$('#question').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();adaptive()}};$('.chips').onclick=e=>{if(e.target.tagName==='BUTTON'){$('#question').value=e.target.textContent;adaptive()}};addEventListener('resize',()=>!(['adaptable','powerbi'].includes(view)||view.startsWith('tableau-'))&&render());init();
