function escapeHtml(value){const node=document.createElement("div");node.textContent=String(value??"");return node.innerHTML}
function dashboardValue(item){const value=Number(item.value||0);if(item.format==="currency")return value.toLocaleString("es-CO",{style:"currency",currency:"USD"});if(item.format==="percent")return value.toLocaleString("es-CO",{maximumFractionDigits:2})+"%";return value.toLocaleString("es-CO")}
function attachDashboard(bubble,spec){const root=document.createElement("section");root.className="ai-dashboard";root.innerHTML='<header class="dashboard-head"><div><small>DASHBOARD GENERADO POR IA</small><h2>'+escapeHtml(spec.title||"Dashboard ejecutivo")+"</h2><p>"+escapeHtml(spec.subtitle||"")+'</p></div><button class="primary dashboard-download">Descargar PNG</button></header>';const kpis=document.createElement("div");kpis.className="dashboard-kpis";(spec.kpis||[]).forEach(item=>{const card=document.createElement("article");card.innerHTML="<small>"+escapeHtml(item.label)+"</small><strong>"+escapeHtml(dashboardValue(item))+"</strong>";kpis.appendChild(card)});root.appendChild(kpis);const charts=document.createElement("div");charts.className="dashboard-charts";(spec.charts||[]).forEach(chart=>{const card=document.createElement("article");card.className="dashboard-chart";attachChart(card,chart);charts.appendChild(card)});root.appendChild(charts);root.querySelector(".dashboard-download").addEventListener("click",()=>downloadDashboard(spec));bubble.appendChild(root)}
function dashboardCanvasText(ctx,text,x,y,font,color="#10243e"){ctx.font=font;ctx.fillStyle=color;ctx.fillText(String(text),x,y)}
function dashboardWrapText(ctx,text,x,y,maxWidth,lineHeight,maxLines=2){const words=String(text||"").split(/\s+/);let line="",lines=[];for(const word of words){const test=line?line+" "+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((part,i)=>ctx.fillText(part+(i===maxLines-1&&lines.length>maxLines?"…":""),x,y+i*lineHeight))}
function dashboardChartHeight(chart){if(chart.type==="heatmap")return Math.max(330,(chart.y_labels||[]).length*28+85);if(chart.type==="stacked_bar")return 380;if(chart.type==="boxplot"||chart.type==="pareto"||chart.secondary_axis)return 340;if(chart.orientation==="horizontal")return Math.max(280,(chart.labels||[]).length*32+35);if(["pie","doughnut"].includes(chart.type))return 340;return 300}
function downloadDashboard(spec){
 const width=1400,margin=55,gap=24,chartW=(width-margin*2-gap)/2,charts=spec.charts||[];
 const rowHeights=[];for(let i=0;i<charts.length;i+=2){rowHeights.push(Math.max(...charts.slice(i,i+2).map(chart=>dashboardChartHeight(chart)+175),455))}
 const rowTops=[];let cursor=300;rowHeights.forEach(height=>{rowTops.push(cursor);cursor+=height+gap});const height=cursor+35;
 const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d");ctx.fillStyle="#f4f7fa";ctx.fillRect(0,0,width,height);ctx.fillStyle="#12384b";ctx.fillRect(0,0,width,125);
 ctx.font="bold 24px Arial";ctx.fillStyle="#fff";dashboardWrapText(ctx,spec.title||"Dashboard ejecutivo",margin,34,width-margin*2,28,2);ctx.font="15px Arial";ctx.fillStyle="#8de8dd";dashboardWrapText(ctx,spec.subtitle||"Fuente: PostgreSQL RopaV",margin,90,width-margin*2,19,2);
 const kpis=spec.kpis||[],kGap=12,kW=(width-margin*2-kGap*(kpis.length-1))/Math.max(kpis.length,1);kpis.forEach((item,i)=>{const x=margin+i*(kW+kGap);ctx.fillStyle="#fff";ctx.fillRect(x,150,kW,105);dashboardCanvasText(ctx,item.label,x+15,181,"bold 13px Arial","#718096");dashboardCanvasText(ctx,dashboardValue(item),x+15,221,"bold 22px Arial")});
 charts.forEach((chart,i)=>{const row=Math.floor(i/2),x=margin+(i%2)*(chartW+gap),y=rowTops[row],cardH=rowHeights[row],chartH=dashboardChartHeight(chart);ctx.fillStyle="#fff";ctx.fillRect(x,y,chartW,cardH);dashboardCanvasText(ctx,chart.title,x+20,y+32,"bold 18px Arial");ctx.font="13px Arial";ctx.fillStyle="#617187";dashboardWrapText(ctx,chart.description||"",x+20,y+57,chartW-40,18,3);const temp=document.createElement("canvas");temp.dataset.renderWidth=String(Math.floor(chartW-36));drawChatChart(temp,chart);ctx.drawImage(temp,x+18,y+105,chartW-36,chartH);let legendY=y+chartH+128,legendX=x+20;const entries=["pie","doughnut"].includes(chart.type)?(chart.labels||[]).map((label,j)=>[label,(chart.colors||[])[j]]):(chart.type==="stacked_bar"?(((chart.stacks||[])[0]||{}).datasets||[]).map(d=>[d.label,d.color]):(chart.datasets||[]).map(d=>[d.label,d.color]));entries.slice(0,8).forEach(([label,color])=>{const itemW=Math.min(190,ctx.measureText(String(label)).width+42);if(legendX+itemW>x+chartW-20){legendX=x+20;legendY+=20}ctx.fillStyle=color||"#11a99a";ctx.fillRect(legendX,legendY-9,10,10);dashboardCanvasText(ctx,label,legendX+16,legendY,"12px Arial","#526177");legendX+=itemW});dashboardCanvasText(ctx,"Fuente: "+(chart.source||"PostgreSQL RopaV"),x+20,y+cardH-18,"11px Arial","#718096")});
 const link=document.createElement("a");link.download=(spec.title||"dashboard").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-")+".png";link.href=canvas.toDataURL("image/png");link.click()
}
