function escapeHtml(value){const node=document.createElement("div");node.textContent=String(value??"");return node.innerHTML}
function dashboardValue(item){const value=Number(item.value||0);if(item.format==="currency")return value.toLocaleString("es-CO",{style:"currency",currency:"USD"});if(item.format==="percent")return value.toLocaleString("es-CO",{maximumFractionDigits:2})+"%";return value.toLocaleString("es-CO")}
function attachDashboard(bubble,spec){const root=document.createElement("section");root.className="ai-dashboard";root.innerHTML='<header class="dashboard-head"><div><small>DASHBOARD GENERADO POR IA</small><h2>'+escapeHtml(spec.title||"Dashboard ejecutivo")+"</h2><p>"+escapeHtml(spec.subtitle||"")+'</p></div><button class="primary dashboard-download">Descargar PNG</button></header>';const kpis=document.createElement("div");kpis.className="dashboard-kpis";(spec.kpis||[]).forEach(item=>{const card=document.createElement("article");card.innerHTML="<small>"+escapeHtml(item.label)+"</small><strong>"+escapeHtml(dashboardValue(item))+"</strong>";kpis.appendChild(card)});root.appendChild(kpis);const charts=document.createElement("div");charts.className="dashboard-charts";(spec.charts||[]).forEach(chart=>{const card=document.createElement("article");card.className="dashboard-chart";attachChart(card,chart);charts.appendChild(card)});root.appendChild(charts);root.querySelector(".dashboard-download").addEventListener("click",()=>downloadDashboard(spec));bubble.appendChild(root)}
function dashboardCanvasText(ctx,text,x,y,font,color="#10243e"){ctx.font=font;ctx.fillStyle=color;ctx.fillText(String(text),x,y)}
function dashboardWrapText(ctx,text,x,y,maxWidth,lineHeight,maxLines=2){const words=String(text||"").split(/\s+/);let line="",lines=[];for(const word of words){const test=line?line+" "+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((part,i)=>ctx.fillText(part+(i===maxLines-1&&lines.length>maxLines?"…":""),x,y+i*lineHeight))}
function dashboardChartHeight(chart){if(chart.type==="heatmap")return Math.max(330,(chart.y_labels||[]).length*28+85);if(chart.type==="stacked_bar")return 380;if(chart.type==="boxplot"||chart.type==="pareto"||chart.secondary_axis)return 340;if(chart.orientation==="horizontal")return Math.max(280,(chart.labels||[]).length*32+35);if(["pie","doughnut"].includes(chart.type))return 340;return 300}
function downloadDashboard(spec){
 const width=1400,margin=55,gap=24,chartW=(width-margin*2-gap)/2,charts=spec.charts||[];
 const exports=charts.map(chart=>chartExportCanvas(chart,Math.floor(chartW))); const rowHeights=[];for(let i=0;i<charts.length;i+=2){rowHeights.push(Math.max(...exports.slice(i,i+2).map(canvas=>canvas.height*chartW/canvas.width),200))}
 const rowTops=[];let cursor=300;rowHeights.forEach(height=>{rowTops.push(cursor);cursor+=height+gap});const height=cursor+35;
 const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d");ctx.fillStyle="#f4f7fa";ctx.fillRect(0,0,width,height);ctx.fillStyle="#12384b";ctx.fillRect(0,0,width,125);
 ctx.font="bold 24px Arial";ctx.fillStyle="#fff";dashboardWrapText(ctx,spec.title||"Dashboard ejecutivo",margin,34,width-margin*2,28,2);ctx.font="15px Arial";ctx.fillStyle="#8de8dd";dashboardWrapText(ctx,spec.subtitle||"Fuente: PostgreSQL RopaV",margin,90,width-margin*2,19,2);
 const kpis=spec.kpis||[],kGap=12,kW=(width-margin*2-kGap*(kpis.length-1))/Math.max(kpis.length,1);kpis.forEach((item,i)=>{const x=margin+i*(kW+kGap);ctx.fillStyle="#fff";ctx.fillRect(x,150,kW,105);ctx.font="bold 12px Arial";ctx.fillStyle="#718096";dashboardWrapText(ctx,item.label,x+15,175,kW-30,14,3);dashboardCanvasText(ctx,dashboardValue(item),x+15,239,"bold 22px Arial")});
 charts.forEach((chart,i)=>{const row=Math.floor(i/2),x=margin+(i%2)*(chartW+gap),y=rowTops[row],exported=exports[i];ctx.fillStyle="#fff";ctx.fillRect(x,y,chartW,rowHeights[row]);ctx.drawImage(exported,x,y,chartW,exported.height*chartW/exported.width)});
 const link=document.createElement("a");link.download=(spec.title||"dashboard").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-")+".png";link.href=canvas.toDataURL("image/png");link.click()
}
